// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZyFUR_ybM3pfW9J2d_E1CCHGjJRubno8',
    appId: '1:895762929597:web:6c804d5ab2fa879c16a4d4',
    messagingSenderId: '895762929597',
    projectId: 'saveameal-87187',
    authDomain: 'saveameal-87187.firebaseapp.com',
    storageBucket: 'saveameal-87187.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW_7MmI_P9zYgEmXcfBGLyj8N_kcLPPgk',
    appId: '1:895762929597:android:dd1969a68407b7b716a4d4',
    messagingSenderId: '895762929597',
    projectId: 'saveameal-87187',
    storageBucket: 'saveameal-87187.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJzYUS0k4l-hgcwslhj-3vL_72qfIse4',
    appId: '1:895762929597:ios:8b6317a033f04b1716a4d4',
    messagingSenderId: '895762929597',
    projectId: 'saveameal-87187',
    storageBucket: 'saveameal-87187.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJzYUS0k4l-hgcwslhj-3vL_72qfIse4',
    appId: '1:895762929597:ios:8b6317a033f04b1716a4d4',
    messagingSenderId: '895762929597',
    projectId: 'saveameal-87187',
    storageBucket: 'saveameal-87187.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZyFUR_ybM3pfW9J2d_E1CCHGjJRubno8',
    appId: '1:895762929597:web:93b605e938e1100516a4d4',
    messagingSenderId: '895762929597',
    projectId: 'saveameal-87187',
    authDomain: 'saveameal-87187.firebaseapp.com',
    storageBucket: 'saveameal-87187.firebasestorage.app',
  );
}
